trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

strategy:
  matrix:
    node_10_x:
      node_version: 10.x
    node_12_x:
      node_version: 12.x

steps:
- task: NodeTool@0
  displayName: Install Node.js
  inputs:
    versionSpec: $(node_version)

- bash: npm ci
  displayName: Install dependencies

- bash: npm run test:azure
  displayName: Test

- bash: npm run build:azure
  displayName: Build

- task: PublishTestResults@2
  displayName: Publish test results
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: 'junit.xml'
